# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('model', models.CharField(db_index=True, max_length=200)),
                ('price', models.FloatField(null=True)),
                ('contacts', models.TextField()),
            ],
        ),
    ]
